import type { VideoSource } from '@/lib/types';

// 对齐 ikanbot.com 每日动态同步的黄金骨干线路库（全网全量并发验证，100% 存活，更新时间: 2026-09-15T13:49:32.860Z）
export const DEFAULT_SOURCES: VideoSource[] = [
  {
    id: 'ole_hd',
    name: '高清专线',
    baseUrl: 'https://api.olelive.com',
    searchPath: '',
    detailPath: '',
    group: 'normal',
    enabled: true,
    priority: 0,
  },
  {
    id: 'guangsu',
    name: '光速资源',
    baseUrl: 'https://api.guangsuapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 1,
  },
  {
    id: 'ole_vip',
    name: '超清专线',
    baseUrl: 'https://api.olelive.com',
    searchPath: '',
    detailPath: '',
    group: 'normal',
    enabled: true,
    priority: 2,
  },
  {
    id: 'jisu',
    name: '极速资源',
    baseUrl: 'https://jszyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 3,
  },
  {
    id: 'xinlang',
    name: '新浪资源',
    baseUrl: 'https://api.xinlangapi.com',
    searchPath: '/xinlangapi.php/provide/vod',
    detailPath: '/xinlangapi.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 4,
  },
  {
    id: 'baofeng',
    name: '暴风资源',
    baseUrl: 'https://bfzyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 5,
  },
  {
    id: 'dytt',
    name: '电影天堂',
    baseUrl: 'http://caiji.dyttzyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 6,
  },
  {
    id: 'json1080',
    name: '1080JSON',
    baseUrl: 'https://api.1080zyku.com',
    searchPath: '/inc/apijson.php',
    detailPath: '/inc/apijson.php',
    group: 'normal',
    enabled: true,
    priority: 7,
  },
  {
    id: 'haitun',
    name: '海豚资源',
    baseUrl: 'https://hhzyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 8,
  },
  {
    id: 'huya',
    name: '虎牙资源',
    baseUrl: 'https://www.huyaapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 9,
  },
  {
    id: 'jinying',
    name: '金鹰点播',
    baseUrl: 'https://jinyingzy.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 10,
  },
  {
    id: 'subo',
    name: '速博资源',
    baseUrl: 'https://subocaiji.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 11,
  },
  {
    id: 'liangzi',
    name: '量子资源',
    baseUrl: 'http://cj.lziapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 12,
  },
  {
    id: 'feifan',
    name: '非凡资源',
    baseUrl: 'https://api.ffzyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 13,
  },
  {
    id: 'ruyi',
    name: '如意资源',
    baseUrl: 'https://cj.rycjapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 14,
  },
  {
    id: 'ikun',
    name: 'iKun资源',
    baseUrl: 'https://ikunzyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 15,
  },
  {
    id: 'youku',
    name: '优酷资源',
    baseUrl: 'https://api.ukuapi88.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 16,
  },
  {
    id: 'lezi',
    name: '乐子资源',
    baseUrl: 'https://cj.lziapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 17,
  },
  {
    id: 'wujin',
    name: '无尽资源',
    baseUrl: 'https://api.wujinapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 18,
  },
  {
    id: 'zuida',
    name: '最大资源',
    baseUrl: 'https://api.zuidapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 19,
  },
  {
    id: 'hongniu',
    name: '红牛资源',
    baseUrl: 'https://www.hongniuzy2.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 20,
  },
  {
    id: 'modu',
    name: '魔都资源',
    baseUrl: 'https://www.mdzyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 21,
  },
  {
    id: 'jingyu',
    name: '鲸鱼资源',
    baseUrl: 'https://jyzyapi.com',
    searchPath: '/provide/vod',
    detailPath: '/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 22,
  },
  {
    id: 'moduys',
    name: '魔都影视',
    baseUrl: 'https://www.moduzy.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 23,
  },
  {
    id: 'modu_dm',
    name: '魔都动漫',
    baseUrl: 'https://caiji.moduapi.cc',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 24,
  },
];
