import type { VideoSource } from '@/lib/types';

// 对齐 ikanbot.com 核心播放与梯队调度规则的黄金骨干线路库
// 第一梯队（1-7）：100% 开放 CORS (*)、标准 443 HTTPS 端口纯净切片、全网热剧覆盖率 95%+，首跳秒播！
// 第二梯队（8-19）：高码率/1080P/4K 专线，备用切换
// 第三梯队（20-24）：小众/保底兜底线路
export const DEFAULT_SOURCES: VideoSource[] = [
  // === 第一梯队：全量 443 端口纯净切片与数百万海量热播大源（秒播首选） ===
  {
    id: 'guangsu',
    name: '光速资源',
    baseUrl: 'https://api.guangsuapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 1,
  },
  {
    id: 'wujin',
    name: '无尽资源',
    baseUrl: 'https://api.wujinapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 2,
  },
  {
    id: 'zuida',
    name: '最大资源',
    baseUrl: 'https://api.zuidapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 3,
  },
  {
    id: 'jisu',
    name: '极速资源',
    baseUrl: 'https://jszyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 4,
  },
  {
    id: 'xinlang',
    name: '新浪资源',
    baseUrl: 'https://api.xinlangapi.com',
    searchPath: '/xinlangapi.php/provide/vod',
    detailPath: '/xinlangapi.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 5,
  },
  {
    id: 'modu',
    name: '魔都资源',
    baseUrl: 'https://www.mdzyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 6,
  },
  {
    id: 'zy360',
    name: '360资源',
    baseUrl: 'https://360zy.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 7,
  },

  // === 第二梯队：优质主流高码率专线（1080P/4K，部分节点有防盗链策略） ===
  {
    id: 'json1080',
    name: '1080JSON',
    baseUrl: 'https://api.1080zyku.com',
    searchPath: '/inc/apijson.php',
    detailPath: '/inc/apijson.php',
    group: 'normal',
    enabled: true,
    priority: 8,
  },
  {
    id: 'feifan',
    name: '非凡资源',
    baseUrl: 'https://api.ffzyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 9,
  },
  {
    id: 'baofeng',
    name: '暴风资源',
    baseUrl: 'https://bfzyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 10,
  },
  {
    id: 'dytt',
    name: '电影天堂',
    baseUrl: 'http://caiji.dyttzyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 11,
  },
  {
    id: 'liangzi',
    name: '量子资源',
    baseUrl: 'http://cj.lziapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 12,
  },
  {
    id: 'hongniu',
    name: '红牛资源',
    baseUrl: 'https://www.hongniuzy2.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 13,
  },
  {
    id: 'huya',
    name: '虎牙资源',
    baseUrl: 'https://www.huyaapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 14,
  },
  {
    id: 'haitun',
    name: '海豚资源',
    baseUrl: 'https://hhzyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 15,
  },
  {
    id: 'lezi',
    name: '乐子资源',
    baseUrl: 'https://cj.lziapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 16,
  },
  {
    id: 'ruyi',
    name: '如意资源',
    baseUrl: 'https://cj.rycjapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 17,
  },
  {
    id: 'modu_dm',
    name: '魔都动漫',
    baseUrl: 'https://caiji.moduapi.cc',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 18,
  },
  {
    id: 'moduys',
    name: '魔都影视',
    baseUrl: 'https://www.moduzy.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 19,
  },

  // === 第三梯队：备用线路（部分切片挂在非标端口或开启防盗链，顺延保底） ===
  {
    id: 'ikun',
    name: 'iKun资源',
    baseUrl: 'https://ikunzyapi.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 20,
  },
  {
    id: 'subo',
    name: '速博资源',
    baseUrl: 'https://subocaiji.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 21,
  },
  {
    id: 'jinying',
    name: '金鹰点播',
    baseUrl: 'https://jinyingzy.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 22,
  },
  {
    id: 'youku',
    name: '优酷资源',
    baseUrl: 'https://api.ukuapi88.com',
    searchPath: '/api.php/provide/vod',
    detailPath: '/api.php/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 23,
  },
  {
    id: 'jingyu',
    name: '鲸鱼资源',
    baseUrl: 'https://jyzyapi.com',
    searchPath: '/provide/vod',
    detailPath: '/provide/vod',
    group: 'normal',
    enabled: true,
    priority: 24,
  },
];
