import type { VideoSource } from '@/lib/types';

// 高级模式视频源 (Premium / 18+) — 22 条源
export const PREMIUM_SOURCES: VideoSource[] = [
    {
        id: 'hsck',
        name: '黄色仓库',
        baseUrl: 'https://hsckzy.vip',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 1,
    },
    {
        id: 'leba',
        name: '乐播资源',
        baseUrl: 'https://lbapi9.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 2,
    },
    {
        id: 'ck',
        name: 'CK',
        baseUrl: 'https://www.ckzy1.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 3,
    },
    {
        id: 'jkun',
        name: 'jkun',
        baseUrl: 'https://jkunzyapi.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 4,
    },
    {
        id: '155',
        name: '155',
        baseUrl: 'https://155api.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 5,
    },
    {
        id: 'lsb',
        name: 'lsb',
        baseUrl: 'https://apilsbzy1.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 6,
    },
    {
        id: 'yutu',
        name: '玉兔',
        baseUrl: 'https://yutuzy10.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 7,
    },
    {
        id: 'msnii',
        name: '美少女资源站',
        baseUrl: 'https://www.msnii.com',
        searchPath: '/api/json.php',
        detailPath: '/api/json.php',
        group: 'premium',
        enabled: true,
        priority: 8,
    },
    {
        id: 'xrbsp',
        name: '淫水机资源站',
        baseUrl: 'https://www.xrbsp.com',
        searchPath: '/api/json.php',
        detailPath: '/api/json.php',
        group: 'premium',
        enabled: true,
        priority: 9,
    },
    {
        id: 'gdlsp',
        name: '香奶儿资源站',
        baseUrl: 'https://www.gdlsp.com',
        searchPath: '/api/json.php',
        detailPath: '/api/json.php',
        group: 'premium',
        enabled: true,
        priority: 10,
    },
    {
        id: 'kxgav',
        name: '白嫖资源站',
        baseUrl: 'https://www.kxgav.com',
        searchPath: '/api/json.php',
        detailPath: '/api/json.php',
        group: 'premium',
        enabled: true,
        priority: 11,
    },
    {
        id: 'pgxdy',
        name: '黄AV资源站',
        baseUrl: 'https://www.pgxdy.com',
        searchPath: '/api/json.php',
        detailPath: '/api/json.php',
        group: 'premium',
        enabled: true,
        priority: 12,
    },
    {
        id: 'baiwan',
        name: '百万资源',
        baseUrl: 'https://api.bwzyz.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 13,
    },
    {
        id: 'madou',
        name: '91麻豆',
        baseUrl: 'https://91md.me',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 14,
    },
    {
        id: 'aosika',
        name: '奥斯卡资源',
        baseUrl: 'https://aosikazy.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 15,
    },
    {
        id: 'naixiang',
        name: '奶香香',
        baseUrl: 'https://Naixxzy.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 16,
    },
    {
        id: 'senlin',
        name: '森林资源',
        baseUrl: 'https://slapibf.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 17,
    },
    {
        id: 'fanhao',
        name: '番号资源',
        baseUrl: 'http://fhapi9.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 18,
    },
    {
        id: 'jingpin',
        name: '精品资源',
        baseUrl: 'https://www.jingpinx.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 19,
    },
    {
        id: 'shayu',
        name: '鲨鱼资源',
        baseUrl: 'https://shayuapi.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 20,
    },
    {
        id: 'xiaoji',
        name: '小鸡资源',
        baseUrl: 'https://api.xiaojizy.live',
        searchPath: '/provide/vod',
        detailPath: '/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 21,
    },
    {
        id: 'xibao',
        name: '细胞采集',
        baseUrl: 'https://www.xxibaozyw.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 22,
    },
    {
        id: 'tantan',
        name: '探探资源',
        baseUrl: 'https://ttzy.tv',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 23,
    },
    {
        id: 'sejie',
        name: '色界资源',
        baseUrl: 'https://api.sejie.tv',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 24,
    },
    {
        id: 'semao',
        name: '色猫资源',
        baseUrl: 'https://api.semaozy.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 25,
    },
    {
        id: 'laosiji_4k',
        name: '老司机4K原画',
        baseUrl: 'https://api.laosiji4k.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 26,
    },
    {
        id: 'zhipian_91',
        name: '91制片厂',
        baseUrl: 'https://api.91zhipian.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 27,
    },
    {
        id: 'jiali',
        name: '佳丽极品',
        baseUrl: 'https://api.jializy.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 28,
    },
    {
        id: 'mitao',
        name: '蜜桃传媒',
        baseUrl: 'https://api.mitaozy.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 29,
    },
    {
        id: 'tianmei',
        name: '天美传媒',
        baseUrl: 'https://api.tianmeizy.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 30,
    },
    {
        id: 'xingkong_cm',
        name: '星空传媒',
        baseUrl: 'https://api.xingkongzy.tv',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 31,
    },
    {
        id: 'huangjia',
        name: '皇家华人',
        baseUrl: 'https://api.huangjiazy.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 32,
    },
    {
        id: 'guodong',
        name: '果冻传媒',
        baseUrl: 'https://api.guodongzy.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 33,
    },
    {
        id: 'tangxin',
        name: '糖心Vlog',
        baseUrl: 'https://api.tangxinzy.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 34,
    },
    {
        id: 'fc2_pro',
        name: '精品FC2专线',
        baseUrl: 'https://api.fc2zy.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 35,
    },
    {
        id: 'midnight_4k',
        name: '暗夜极光专线',
        baseUrl: 'https://api.midnight4k.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 36,
    },
];
